#ifndef __GUARD_PROG_TOOLS_GETKEY
    #define __GUARD_PROG_TOOLS_GETKEY

    #include <stdbool.h>
    #include "structs.h"

    #define GETKEY_ARGS     (GETKEY_DEFAULT & ~GETKEY_MENU & ~GETKEY_MOD_SHIFT & ~GETKEY_MOD_ALPHA )

    //Virtual key assignments
    enum VirtualKeys
    {
        //Unmodified keycode not accounting for modifier keys - must appear in this order
        VKEY_NONE,
        VKEY_ACON,
        VKEY_0,
        VKEY_DOT,
        VKEY_EXP,
        VKEY_NEG,
        VKEY_EXE,
        VKEY_1,
        VKEY_2,
        VKEY_3,
        VKEY_ADD,
        VKEY_SUB,
        VKEY_4,
        VKEY_5,
        VKEY_6,
        VKEY_MUL,
        VKEY_DIV,
        VKEY_7,
        VKEY_8,
        VKEY_9,
        VKEY_DEL,
        VKEY_FRAC,
        VKEY_FD,
        VKEY_LEFTP,
        VKEY_RIGHTP,
        VKEY_COMMA,
        VKEY_ARROW,
        VKEY_XOT,
        VKEY_LOG,
        VKEY_LN,
        VKEY_SIN,
        VKEY_COS,
        VKEY_TAN,
        VKEY_ALPHA,
        VKEY_SQUARE,
        VKEY_POWER,
        VKEY_EXIT,
        VKEY_DOWN,
        VKEY_RIGHT,
        VKEY_SHIFT,
        VKEY_OPTN,
        VKEY_VARS,
        VKEY_MENU,
        VKEY_LEFT,
        VKEY_UP,
        VKEY_F1,
        VKEY_F2,
        VKEY_F3,
        VKEY_F4,
        VKEY_F5,
        VKEY_F6,

        //Virtual keys generated with modifier - order not important
        VKEY_ACOFF,
        VKEY_IMAG,
        VKEY_EQUAL,
        VKEY_PI,
        VKEY_ANS,
        VKEY_SHIFT_EXE,
        VKEY_LIST,
        VKEY_MAT,
        VKEY_LSBRACKET,
        VKEY_RSBRACKET,
        VKEY_CATALOG,
        VKEY_FORMAT,
        VKEY_LCBRACKET,
        VKEY_RCBRACKET,
        VKEY_CAPTURE,
        VKEY_CLIP,
        VKEY_PASTE,
        VKEY_INS,
        VKEY_SHIFT_FRAC,
        VKEY_SHIFT_FD,
        VKEY_CUBE_ROOT,
        VKEY_1_X,
        VKEY_NEXT_SCREEN,
        VKEY_SWAP_SCREEN,
        VKEY_ANGLE,
        VKEY_10_X,
        VKEY_E_X,
        VKEY_ASIN,
        VKEY_ACOS,
        VKEY_ATAN,
        VKEY_A_LOCK,
        VKEY_SQRT,
        VKEY_X_ROOT,
        VKEY_QUIT,
        VKEY_SHIFT_DOWN,
        VKEY_SHIFT_RIGHT,
        VKEY_SHIFT_OPTN,
        VKEY_PRGM,
        VKEY_SET_UP,
        VKEY_SHIFT_LEFT,
        VKEY_SHIFT_UP,
        VKEY_SHIFT_F1,
        VKEY_SHIFT_F2,
        VKEY_SHIFT_F3,
        VKEY_SHIFT_F4,
        VKEY_SHIFT_F5,
        VKEY_SHIFT_F6,
        VKEY_Z,
        VKEY_SPACE,
        VKEY_QUOTE,
        VKEY_U,
        VKEY_V,
        VKEY_W,
        VKEY_X,
        VKEY_Y,
        VKEY_P,
        VKEY_Q,
        VKEY_R,
        VKEY_S,
        VKEY_T,
        VKEY_M,
        VKEY_N,
        VKEY_O,
        VKEY_UNDO,
        VKEY_G,
        VKEY_H,
        VKEY_I,
        VKEY_J,
        VKEY_K,
        VKEY_L,
        VKEY_A,
        VKEY_B,
        VKEY_C,
        VKEY_D,
        VKEY_E,
        VKEY_F,
        VKEY_RADIAN,
        VKEY_THETA,
        VKEY_z,
        VKEY_u,
        VKEY_v,
        VKEY_w,
        VKEY_x,
        VKEY_y,
        VKEY_p,
        VKEY_q,
        VKEY_r,
        VKEY_s,
        VKEY_t,
        VKEY_m,
        VKEY_n,
        VKEY_o,
        VKEY_g,
        VKEY_h,
        VKEY_i,
        VKEY_j,
        VKEY_k,
        VKEY_l,
        VKEY_a,
        VKEY_b,
        VKEY_c,
        VKEY_d,
        VKEY_e,
        VKEY_f,
    };

    //Global variables
    extern const int key_shifted[];
    extern const int key_upper[];
    extern const int key_lower[];
    extern const int key_printable[];
    extern const int key_printable_shifted[];
    extern const int key_printable_upper[];
    extern const int key_printable_lower[];

    //Functions
    int getkey_wrapper(bool wait);

#endif
