//TODO: still need all of these? split off from key-remap.h

#include <SDL2/SDL.h>

#include "getkey.h"

//Applied to all programs including ones that have remappings below
struct KeyRemap remapped_keys_all[]=

{
    {SDL_SCANCODE_A,    MODIFIER_NONE,          VKEY_a},
    {SDL_SCANCODE_A,    MODIFIER_ALPHA_LOWER,   VKEY_a},
    {SDL_SCANCODE_A,    MODIFIER_ALPHA_UPPER,   VKEY_A},
    {SDL_SCANCODE_B,    MODIFIER_NONE,          VKEY_b},
    {SDL_SCANCODE_B,    MODIFIER_ALPHA_LOWER,   VKEY_b},
    {SDL_SCANCODE_B,    MODIFIER_ALPHA_UPPER,   VKEY_B},
    {SDL_SCANCODE_C,    MODIFIER_NONE,          VKEY_c},
    {SDL_SCANCODE_C,    MODIFIER_ALPHA_LOWER,   VKEY_c},
    {SDL_SCANCODE_C,    MODIFIER_ALPHA_UPPER,   VKEY_C},
    {SDL_SCANCODE_D,    MODIFIER_NONE,          VKEY_d},
    {SDL_SCANCODE_D,    MODIFIER_ALPHA_LOWER,   VKEY_d},
    {SDL_SCANCODE_D,    MODIFIER_ALPHA_UPPER,   VKEY_D},
    {SDL_SCANCODE_E,    MODIFIER_NONE,          VKEY_e},
    {SDL_SCANCODE_E,    MODIFIER_ALPHA_LOWER,   VKEY_e},
    {SDL_SCANCODE_E,    MODIFIER_ALPHA_UPPER,   VKEY_E},
    {SDL_SCANCODE_F,    MODIFIER_NONE,          VKEY_f},
    {SDL_SCANCODE_F,    MODIFIER_ALPHA_LOWER,   VKEY_f},
    {SDL_SCANCODE_F,    MODIFIER_ALPHA_UPPER,   VKEY_F},
    {SDL_SCANCODE_G,    MODIFIER_NONE,          VKEY_g},
    {SDL_SCANCODE_G,    MODIFIER_ALPHA_LOWER,   VKEY_g},
    {SDL_SCANCODE_G,    MODIFIER_ALPHA_UPPER,   VKEY_G},
    {SDL_SCANCODE_H,    MODIFIER_NONE,          VKEY_h},
    {SDL_SCANCODE_H,    MODIFIER_ALPHA_LOWER,   VKEY_h},
    {SDL_SCANCODE_H,    MODIFIER_ALPHA_UPPER,   VKEY_H},
    {SDL_SCANCODE_I,    MODIFIER_NONE,          VKEY_i},
    {SDL_SCANCODE_I,    MODIFIER_ALPHA_LOWER,   VKEY_i},
    {SDL_SCANCODE_I,    MODIFIER_ALPHA_UPPER,   VKEY_I},
    {SDL_SCANCODE_J,    MODIFIER_NONE,          VKEY_j},
    {SDL_SCANCODE_J,    MODIFIER_ALPHA_LOWER,   VKEY_j},
    {SDL_SCANCODE_J,    MODIFIER_ALPHA_UPPER,   VKEY_J},
    {SDL_SCANCODE_K,    MODIFIER_NONE,          VKEY_k},
    {SDL_SCANCODE_K,    MODIFIER_ALPHA_LOWER,   VKEY_k},
    {SDL_SCANCODE_K,    MODIFIER_ALPHA_UPPER,   VKEY_K},
    {SDL_SCANCODE_L,    MODIFIER_NONE,          VKEY_l},
    {SDL_SCANCODE_L,    MODIFIER_ALPHA_LOWER,   VKEY_l},
    {SDL_SCANCODE_L,    MODIFIER_ALPHA_UPPER,   VKEY_L},
    {SDL_SCANCODE_M,    MODIFIER_NONE,          VKEY_m},
    {SDL_SCANCODE_M,    MODIFIER_ALPHA_LOWER,   VKEY_m},
    {SDL_SCANCODE_M,    MODIFIER_ALPHA_UPPER,   VKEY_M},
    {SDL_SCANCODE_N,    MODIFIER_NONE,          VKEY_n},
    {SDL_SCANCODE_N,    MODIFIER_ALPHA_LOWER,   VKEY_n},
    {SDL_SCANCODE_N,    MODIFIER_ALPHA_UPPER,   VKEY_N},
    {SDL_SCANCODE_O,    MODIFIER_NONE,          VKEY_o},
    {SDL_SCANCODE_O,    MODIFIER_ALPHA_LOWER,   VKEY_o},
    {SDL_SCANCODE_O,    MODIFIER_ALPHA_UPPER,   VKEY_O},
    {SDL_SCANCODE_P,    MODIFIER_NONE,          VKEY_p},
    {SDL_SCANCODE_P,    MODIFIER_ALPHA_LOWER,   VKEY_p},
    {SDL_SCANCODE_P,    MODIFIER_ALPHA_UPPER,   VKEY_P},
    {SDL_SCANCODE_Q,    MODIFIER_NONE,          VKEY_q},
    {SDL_SCANCODE_Q,    MODIFIER_ALPHA_LOWER,   VKEY_q},
    {SDL_SCANCODE_Q,    MODIFIER_ALPHA_UPPER,   VKEY_Q},
    {SDL_SCANCODE_R,    MODIFIER_NONE,          VKEY_r},
    {SDL_SCANCODE_R,    MODIFIER_ALPHA_LOWER,   VKEY_r},
    {SDL_SCANCODE_R,    MODIFIER_ALPHA_UPPER,   VKEY_R},
    {SDL_SCANCODE_S,    MODIFIER_NONE,          VKEY_s},
    {SDL_SCANCODE_S,    MODIFIER_ALPHA_LOWER,   VKEY_s},
    {SDL_SCANCODE_S,    MODIFIER_ALPHA_UPPER,   VKEY_S},
    {SDL_SCANCODE_T,    MODIFIER_NONE,          VKEY_t},
    {SDL_SCANCODE_T,    MODIFIER_ALPHA_LOWER,   VKEY_t},
    {SDL_SCANCODE_T,    MODIFIER_ALPHA_UPPER,   VKEY_T},
    {SDL_SCANCODE_U,    MODIFIER_NONE,          VKEY_u},
    {SDL_SCANCODE_U,    MODIFIER_ALPHA_LOWER,   VKEY_u},
    {SDL_SCANCODE_U,    MODIFIER_ALPHA_UPPER,   VKEY_U},
    {SDL_SCANCODE_V,    MODIFIER_NONE,          VKEY_v},
    {SDL_SCANCODE_V,    MODIFIER_ALPHA_LOWER,   VKEY_v},
    {SDL_SCANCODE_V,    MODIFIER_ALPHA_UPPER,   VKEY_V},
    {SDL_SCANCODE_W,    MODIFIER_NONE,          VKEY_w},
    {SDL_SCANCODE_W,    MODIFIER_ALPHA_LOWER,   VKEY_w},
    {SDL_SCANCODE_W,    MODIFIER_ALPHA_UPPER,   VKEY_W},
    {SDL_SCANCODE_X,    MODIFIER_NONE,          VKEY_x},
    {SDL_SCANCODE_X,    MODIFIER_ALPHA_LOWER,   VKEY_x},
    {SDL_SCANCODE_X,    MODIFIER_ALPHA_UPPER,   VKEY_X},
    {SDL_SCANCODE_Y,    MODIFIER_NONE,          VKEY_y},
    {SDL_SCANCODE_Y,    MODIFIER_ALPHA_LOWER,   VKEY_y},
    {SDL_SCANCODE_Y,    MODIFIER_ALPHA_UPPER,   VKEY_Y},
    {SDL_SCANCODE_Z,    MODIFIER_NONE,          VKEY_z},
    {SDL_SCANCODE_Z,    MODIFIER_ALPHA_LOWER,   VKEY_z},
    {SDL_SCANCODE_Z,    MODIFIER_ALPHA_UPPER,   VKEY_Z},

    {SDL_SCANCODE_1,    MODIFIER_ALPHA_LOWER,   VKEY_1},            //1
    {SDL_SCANCODE_1,    MODIFIER_ALPHA_UPPER,   VKEY_1},            //1
    {SDL_SCANCODE_1,    MODIFIER_SHIFT_NONE,    VKEY_EXCLAMATION},  //1 -> !
    {SDL_SCANCODE_2,    MODIFIER_ALPHA_LOWER,   VKEY_2},            //2
    {SDL_SCANCODE_2,    MODIFIER_ALPHA_UPPER,   VKEY_2},            //2
    {SDL_SCANCODE_2,    MODIFIER_SHIFT_NONE,    VKEY_AT},           //2 -> @
    {SDL_SCANCODE_3,    MODIFIER_ALPHA_LOWER,   VKEY_3},            //3
    {SDL_SCANCODE_3,    MODIFIER_ALPHA_UPPER,   VKEY_3},            //3
    {SDL_SCANCODE_3,    MODIFIER_SHIFT_NONE,    VKEY_HASH},         //3 -> #
    {SDL_SCANCODE_4,    MODIFIER_ALPHA_LOWER,   VKEY_4},            //4
    {SDL_SCANCODE_4,    MODIFIER_ALPHA_UPPER,   VKEY_4},            //4
    {SDL_SCANCODE_4,    MODIFIER_SHIFT_NONE,    VKEY_DOLLAR},       //4 -> $
    {SDL_SCANCODE_5,    MODIFIER_ALPHA_LOWER,   VKEY_5},            //5
    {SDL_SCANCODE_5,    MODIFIER_ALPHA_UPPER,   VKEY_5},            //5
    {SDL_SCANCODE_5,    MODIFIER_SHIFT_NONE,    VKEY_PERCENT},      //5 -> %
    {SDL_SCANCODE_6,    MODIFIER_ALPHA_LOWER,   VKEY_6},            //6
    {SDL_SCANCODE_6,    MODIFIER_ALPHA_UPPER,   VKEY_6},            //6
    {SDL_SCANCODE_6,    MODIFIER_SHIFT_NONE,    VKEY_POWER},        //6 -> ^
    {SDL_SCANCODE_7,    MODIFIER_ALPHA_LOWER,   VKEY_7},            //7
    {SDL_SCANCODE_7,    MODIFIER_ALPHA_UPPER,   VKEY_7},            //7
    {SDL_SCANCODE_7,    MODIFIER_SHIFT_NONE,    VKEY_AMPERSAND},    //7 -> &
    {SDL_SCANCODE_8,    MODIFIER_ALPHA_LOWER,   VKEY_8},            //8
    {SDL_SCANCODE_8,    MODIFIER_ALPHA_UPPER,   VKEY_8},            //8
    {SDL_SCANCODE_8,    MODIFIER_SHIFT_NONE,    VKEY_MUL},          //8 -> *
    {SDL_SCANCODE_9,    MODIFIER_ALPHA_LOWER,   VKEY_9},            //9
    {SDL_SCANCODE_9,    MODIFIER_ALPHA_UPPER,   VKEY_9},            //9
    {SDL_SCANCODE_9,    MODIFIER_SHIFT_NONE,    VKEY_LEFTP},        //9 -> (
    {SDL_SCANCODE_0,    MODIFIER_ALPHA_LOWER,   VKEY_0},            //0
    {SDL_SCANCODE_0,    MODIFIER_ALPHA_UPPER,   VKEY_0},            //0
    {SDL_SCANCODE_0,    MODIFIER_SHIFT_NONE,    VKEY_RIGHTP},       //0 -> )

    //Unshifted tab varies by program - see remappings below
    {SDL_SCANCODE_TAB,  MODIFIER_SHIFT_NONE,    VKEY_FRAC},         //Tab -> fraction key

    {SDL_SCANCODE_SPACE,        MODIFIER_NONE,          VKEY_SPACE},        //Space
    {SDL_SCANCODE_SPACE,        MODIFIER_ALPHA_LOWER,   VKEY_SPACE},        //Space
    {SDL_SCANCODE_SPACE,        MODIFIER_ALPHA_UPPER,   VKEY_SPACE},        //Space
    {SDL_SCANCODE_SPACE,        MODIFIER_SHIFT_NONE,    VKEY_SPACE},        //Space

    {SDL_SCANCODE_MINUS,        MODIFIER_NONE,          VKEY_SUB},          //-
    {SDL_SCANCODE_MINUS,        MODIFIER_ALPHA_LOWER,   VKEY_SUB},          //-
    {SDL_SCANCODE_MINUS,        MODIFIER_ALPHA_UPPER,   VKEY_SUB},          //-
    {SDL_SCANCODE_MINUS,        MODIFIER_SHIFT_NONE,    VKEY_UNDERSCORE},   //- -> _
    {SDL_SCANCODE_EQUALS,       MODIFIER_NONE,          VKEY_EQUAL},        //=
    {SDL_SCANCODE_EQUALS,       MODIFIER_ALPHA_LOWER,   VKEY_EQUAL},        //=
    {SDL_SCANCODE_EQUALS,       MODIFIER_ALPHA_UPPER,   VKEY_EQUAL},        //=
    {SDL_SCANCODE_EQUALS,       MODIFIER_SHIFT_NONE,    VKEY_ADD},          //= -> +
    {SDL_SCANCODE_LEFTBRACKET,  MODIFIER_ALPHA_LOWER,   VKEY_LSBRACKET},    //[
    {SDL_SCANCODE_LEFTBRACKET,  MODIFIER_ALPHA_UPPER,   VKEY_LSBRACKET},    //[
    {SDL_SCANCODE_LEFTBRACKET,  MODIFIER_NONE,          VKEY_LSBRACKET},    //[
    {SDL_SCANCODE_LEFTBRACKET,  MODIFIER_SHIFT_NONE,    VKEY_LCBRACKET},    //[ -> {
    {SDL_SCANCODE_RIGHTBRACKET, MODIFIER_NONE,          VKEY_RSBRACKET},    //]
    {SDL_SCANCODE_RIGHTBRACKET, MODIFIER_ALPHA_LOWER,   VKEY_RSBRACKET},    //]
    {SDL_SCANCODE_RIGHTBRACKET, MODIFIER_ALPHA_UPPER,   VKEY_RSBRACKET},    //]
    {SDL_SCANCODE_RIGHTBRACKET, MODIFIER_SHIFT_NONE,    VKEY_RCBRACKET},    //] -> }
    {SDL_SCANCODE_BACKSLASH,    MODIFIER_NONE,          VKEY_BACKSLASH},    //Backslash
    {SDL_SCANCODE_BACKSLASH,    MODIFIER_ALPHA_LOWER,   VKEY_BACKSLASH},    //Backslash
    {SDL_SCANCODE_BACKSLASH,    MODIFIER_ALPHA_UPPER,   VKEY_BACKSLASH},    //Backslash
    {SDL_SCANCODE_BACKSLASH,    MODIFIER_SHIFT_NONE,    VKEY_PIPE},         //Backslash -> |
    {SDL_SCANCODE_SEMICOLON,    MODIFIER_NONE,          VKEY_SEMICOLON},    //;
    {SDL_SCANCODE_SEMICOLON,    MODIFIER_ALPHA_LOWER,   VKEY_SEMICOLON},    //;
    {SDL_SCANCODE_SEMICOLON,    MODIFIER_ALPHA_UPPER,   VKEY_SEMICOLON},    //;
    {SDL_SCANCODE_SEMICOLON,    MODIFIER_SHIFT_NONE,    VKEY_COLON},        //; -> :
    {SDL_SCANCODE_APOSTROPHE,   MODIFIER_NONE,          VKEY_APOSTROPHE},   //'
    {SDL_SCANCODE_APOSTROPHE,   MODIFIER_ALPHA_LOWER,   VKEY_APOSTROPHE},   //'
    {SDL_SCANCODE_APOSTROPHE,   MODIFIER_ALPHA_UPPER,   VKEY_APOSTROPHE},   //'
    {SDL_SCANCODE_APOSTROPHE,   MODIFIER_SHIFT_NONE,    VKEY_QUOTE},        //' -> "
    {SDL_SCANCODE_COMMA,        MODIFIER_NONE,          VKEY_COMMA},        //,
    {SDL_SCANCODE_COMMA,        MODIFIER_ALPHA_LOWER,   VKEY_COMMA},        //,
    {SDL_SCANCODE_COMMA,        MODIFIER_ALPHA_UPPER,   VKEY_COMMA},        //,
    {SDL_SCANCODE_COMMA,        MODIFIER_SHIFT_NONE,    VKEY_LESS_THAN},    //, -> <
    {SDL_SCANCODE_PERIOD,       MODIFIER_NONE,          VKEY_DOT},          //.
    {SDL_SCANCODE_PERIOD,       MODIFIER_ALPHA_LOWER,   VKEY_DOT},          //.
    {SDL_SCANCODE_PERIOD,       MODIFIER_ALPHA_UPPER,   VKEY_DOT},          //.
    {SDL_SCANCODE_PERIOD,       MODIFIER_SHIFT_NONE,    VKEY_GREATER_THAN}, //. -> >
    {SDL_SCANCODE_SLASH,        MODIFIER_NONE,          VKEY_DIV},          // /
    {SDL_SCANCODE_SLASH,        MODIFIER_ALPHA_LOWER,   VKEY_DIV},          // /
    {SDL_SCANCODE_SLASH,        MODIFIER_ALPHA_UPPER,   VKEY_DIV},          // /
    {SDL_SCANCODE_SLASH,        MODIFIER_SHIFT_NONE,    VKEY_QUESTION},     // / -> ?

    //Marks end of list - DO NOT REMOVE!
    {0,0,0}
};

//Applied only to Forth prompt and Forth programs
struct KeyRemap forth_keys[]=
{

    {SDL_SCANCODE_TAB,  MODIFIER_NONE,          VKEY_ARROW},        //Tab -> arrow

    //Marks end of list - DO NOT REMOVE!
    {0,0,0}
};

